name: Node.js CI

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [18.x] # uWebSockets has blacklisted 16.x
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run postgres test
      run: node ./postgres.test.mjs

    - name: Run redis test
      run: node ./redis.test.mjs

    - name: Run base32 tests
      run: node ./base32.test.mjs

    - name: Run hs256 tests
      run: node ./hs256.test.mjs

    - name: Run csv tests
      run: node ./csv.test.mjs

    - name: Run casefold tests
      run: node ./casefold.test.mjs

    - name: Run uwu tests
      run: node ./uwu.test.mjs
